spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    datasource:
      driver-class-name: com.mysql.cj.jdbc.Driver
      username: root
      password: firoze28
      url: jdbc:mysql://localhost:3306/streambookdb
  mail:
    host: localhost
    port: 1025
    username: firoze
    password: firoze28
    properties:
      mail:
        smtp:
          trust: "*"
        auth: true
        starttls:
          enable: true
        connectiontimeout: 5000
        timeout: 3000
        writetimeout: 5000

application:
 security:
   jwt:
     secret-key: 0ed3e5666e34e213e129671e441fa9f4454ac92ef48740e5811390734f2f6f9a
     expiration: 922882
 mailing:
   frontend:
     activation-url: http://localhost:4200/activate-account
server:
  port: 8085